name: Front-End CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: npm install
    - name: Run Lint
      run: npm run lint
    - name: Validate HTML
      run: npm run validate-html
